#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# build
name: build-cancro-kernel

on:
  workflow_dispatch:


jobs:

  build:

    name: build-cancro-kernel

    runs-on: ubuntu-latest
    environment: TEL
    #if: github.event.repository.owner.id == github.event.sender.id
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        

 
        
      - name: Clone source code
        run: |
          
          git clone https://github.com/vasishath/kernel_cancro.git --depth 1 -b LA.BR.1.3.6_rb1.19
          
          #tar -xf gcc-linaro-12.1.1-2022.07-x86_64_arm-linux-gnueabihf.tar.xz
          git clone https://github.com/Akianonymus/Linaro-arm  --depth 1 -b 4.9
          ls -l
          df -h
        
 

      - name: Compile
        run: |
          ls -l
          export CROSS_COMPILE=$(pwd)/Linaro-arm/bin/arm-eabi-
          export ARCH=arm
          #export PATH="$(pwd)/arm-linux-androideabi-4.9/bin:${PATH}"
          cd kernel_cancro
          
          make cyanogen_cancro_defconfig
          cp ../_.config ./.config
          cp ../memcontrol.c mm
          cp ../dtc-parser.tab.c_shipped scripts/dtc
          cp ../cpuset.c kernel
          make -j1 V=s
          cp ../buildBootimg.sh ./
          chmod +x ./buildBootimg.sh
          ./buildBootimg.sh
          
          cd AnyKernel3
          curl -F document=@kernel-cancro.zip "https://api.telegram.org/bot${TOKEN}/sendDocument"  -F chat_id="${CHAT_ID}" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="test"
          df -h
        env:
          TOKEN: ${{secrets.TOKEN}}
          CHAT_ID: ${{secrets.CHAT_ID}}
