name: build

on:
  workflow_dispatch:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    environment: TEL
    # Docker Hub image that `container-job` executes in
    container: nexgang/ubuntu:latest
    steps:
      #Downloads
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: MotorolaMobilityLLC/kernel-msm
          ref: android-12-release-s3rxc32.33-8-25
          path: kernel
      - name: build
        run: |
          cd kernel
          cp ../build.sh .
          bash build.sh
        env:
          token: ${{secrets.TOKEN}}
          chat_id: ${{secrets.CHAT_ID}}
