name: build

on:
  workflow_dispatch:

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    environment: TEL
    # Docker Hub image that `container-job` executes in
    container: nexgang/ubuntu:latest
    steps:
      #Downloads
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: build
        run: |
          wget -q https://github.com/MotorolaMobilityLLC/kernel-msm/archive/refs/tags/MMI-S3RXC32.33-8-25.tar.gz
          tar -xf MMI*
          cd kernel-m*
          cp ../build.sh .
          bash build.sh
        env:
          token: ${{secrets.TOKEN}}
          chat_id: ${{secrets.CHAT_ID}}
